# Generated by Django 6.0.4 on 2026-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_premiumsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
