# Generated by Django 6.0.4 on 2026-04-11 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_premiumsubscription_ended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifetime_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscountReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='€10 Discount Voucher', max_length=100)),
                ('points_cost', models.PositiveIntegerField(default=200)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(default='Free Ticket Raffle', max_length=150)),
                ('points_cost', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('won', 'Won'), ('lost', 'Lost')], default='joined', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
