# Generated by Django 6.0.4 on 2026-04-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_lifetime_points_profile_premium_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('premium', 'Premium'), ('manager', 'Manager')], default='user', max_length=20),
        ),
    ]
