# Generated by Django 6.0.4 on 2026-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
    ]
